In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score

In [4]:
import nltk 
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
x =  ps.stem('happiness')
print(x)

happi


In [5]:
df=""
df = pd.read_csv("ecommerceDataset copy.csv")
df.head()

Household  \
0  Household   
1  Household   
2  Household   
3  Household   
4  Household   

  Paper Plane Design Framed Wall Hanging Motivational Office Decor Art Prints (8.7 X 8.7 inch) - Set of 4 Painting made up in synthetic frame with uv textured print which gives multi effects and attracts towards it. This is an special series of paintings which makes your wall very beautiful and gives a royal touch. This painting is ready to hang, you would be proud to possess this unique painting that is a niche apart. We use only the most modern and efficient printing technology on our prints, with only the and inks and precision epson, roland and hp printers. This innovative hd printing technique results in durable and spectacular looking prints of the highest that last a lifetime. We print solely with top-notch 100% inks, to achieve brilliant and true colours. Due to their high level of uv resistance, our prints retain their beautiful colours for many years. Add colour and style to your living space with this digitally printed painting. Some are for pleasure and some for eternal bliss.so bring home this elegant print that is lushed with rich colors that makes it nothing but sheer elegance to be to your friends and family.it would be treasured forever by whoever your lucky recipient is. Liven up your place with these intriguing paintings that are high definition hd graphic digital prints for home, office or any room.  
0  SAF 'Floral' Framed Painting (Wood, 30 inch x ...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
1  SAF 'UV Textured Modern Art Print Framed' Pain...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

In [6]:
df.info(verbose=True)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50424 entries, 0 to 50423
Data columns (total 2 columns):
 #   Column                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

In [7]:
df.columns.values[1] = 'content'
df.rename(columns = {'Household':'type'}, inplace = True)
df.head()

type                                            content
0  Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
1  Household  SAF 'UV Textured Modern Art Print Framed' Pain...
2  Household  SAF Flower Print Framed Painting (Synthetic, 1...
3  Household  Incredible Gifts India Wooden Happy Birthday U...
4  Household  Pitaara Box Romantic Venice Canvas Painting 6m...

In [8]:
import nltk 
from nltk.stem import PorterStemmer 
from nltk.tokenize import TreebankWordTokenizer

tokenizer = TreebankWordTokenizer()
ps = PorterStemmer()

df['content'] = df['content'].str.lower()
df['content'] = df['content'].str.replace(r'[^\w\s]', ' ', regex=True)

df['content'] = df['content'].apply(lambda x: tokenizer.tokenize(str(x)))
df['content'] = df['content'].apply(lambda x: [ps.stem(word) for word in x])
df.head()



type                                            content
0  Household  [saf, floral, frame, paint, wood, 30, inch, x,...
1  Household  [saf, uv, textur, modern, art, print, frame, p...
2  Household  [saf, flower, print, frame, paint, synthet, 13...
3  Household  [incred, gift, india, wooden, happi, birthday,...
4  Household  [pitaara, box, romant, venic, canva, paint, 6m...

In [9]:
import nltk
from nltk.util import ngrams
from sklearn.feature_extraction.text import CountVectorizer
from collections import Counter
from nltk.collocations import *

In [10]:
#x = df['content']
shortData= df['content'][0]
print(shortData)
#combined_list = [item for sublist in x for item in sublist]
#print(combined_list)

['saf', 'floral', 'frame', 'paint', 'wood', '30', 'inch', 'x', '10', 'inch', 'special', 'effect', 'uv', 'print', 'textur', 'sao297', 'paint', 'made', 'up', 'in', 'synthet', 'frame', 'with', 'uv', 'textur', 'print', 'which', 'give', 'multi', 'effect', 'and', 'attract', 'toward', 'it', 'thi', 'is', 'an', 'special', 'seri', 'of', 'paint', 'which', 'make', 'your', 'wall', 'veri', 'beauti', 'and', 'give', 'a', 'royal', 'touch', 'a', 'perfect', 'gift', 'for', 'your', 'special', 'one']


In [19]:

def extract_gram(data, num):
        n_grams = ngrams( data, num)
        return [" ".join(grams) for grams in n_grams]


print("1-gram: ", extract_gram( shortData,1))
print("2-gram: ", extract_gram( shortData,2))
print("3-gram: ", extract_gram( shortData,3))

1-gram:  ['saf', 'floral', 'frame', 'paint', 'wood', '30', 'inch', 'x', '10', 'inch', 'special', 'effect', 'uv', 'print', 'textur', 'sao297', 'paint', 'made', 'up', 'in', 'synthet', 'frame', 'with', 'uv', 'textur', 'print', 'which', 'give', 'multi', 'effect', 'and', 'attract', 'toward', 'it', 'thi', 'is', 'an', 'special', 'seri', 'of', 'paint', 'which', 'make', 'your', 'wall', 'veri', 'beauti', 'and', 'give', 'a', 'royal', 'touch', 'a', 'perfect', 'gift', 'for', 'your', 'special', 'one']
2-gram:  ['saf floral', 'floral frame', 'frame paint', 'paint wood', 'wood 30', '30 inch', 'inch x', 'x 10', '10 inch', 'inch special', 'special effect', 'effect uv', 'uv print', 'print textur', 'textur sao297', 'sao297 paint', 'paint made', 'made up', 'up in', 'in synthet', 'synthet frame', 'frame with', 'with uv', 'uv textur', 'textur print', 'print which', 'which give', 'give multi', 'multi effect', 'effect and', 'and attract', 'attract toward', 'toward it', 'it thi', 'thi is', 'is an', 'an special'

In [25]:

def Count(pairs):
    fd=nltk.FreqDist(pairs)
    print(fd.keys())
    print (fd.values())
    for k,v in fd.items():
        print (k,v)


Count(extract_gram(shortData,2))

dict_keys(['saf floral', 'floral frame', 'frame paint', 'paint wood', 'wood 30', '30 inch', 'inch x', 'x 10', '10 inch', 'inch special', 'special effect', 'effect uv', 'uv print', 'print textur', 'textur sao297', 'sao297 paint', 'paint made', 'made up', 'up in', 'in synthet', 'synthet frame', 'frame with', 'with uv', 'uv textur', 'textur print', 'print which', 'which give', 'give multi', 'multi effect', 'effect and', 'and attract', 'attract toward', 'toward it', 'it thi', 'thi is', 'is an', 'an special', 'special seri', 'seri of', 'of paint', 'paint which', 'which make', 'make your', 'your wall', 'wall veri', 'veri beauti', 'beauti and', 'and give', 'give a', 'a royal', 'royal touch', 'touch a', 'a perfect', 'perfect gift', 'gift for', 'for your', 'your special', 'special one'])
dict_values([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
saf floral 1
floral fr

In [21]:
def CountCounter():
    bigram= extract_gram(shortData,1)
    print (Counter(bigram))
CountCounter()

Counter({'paint': 3, 'special': 3, 'frame': 2, 'inch': 2, 'effect': 2, 'uv': 2, 'print': 2, 'textur': 2, 'which': 2, 'give': 2, 'and': 2, 'your': 2, 'a': 2, 'saf': 1, 'floral': 1, 'wood': 1, '30': 1, 'x': 1, '10': 1, 'sao297': 1, 'made': 1, 'up': 1, 'in': 1, 'synthet': 1, 'with': 1, 'multi': 1, 'attract': 1, 'toward': 1, 'it': 1, 'thi': 1, 'is': 1, 'an': 1, 'seri': 1, 'of': 1, 'make': 1, 'wall': 1, 'veri': 1, 'beauti': 1, 'royal': 1, 'touch': 1, 'perfect': 1, 'gift': 1, 'for': 1, 'one': 1})


In [12]:
df['content'] = df['content'].apply(lambda x: ' '.join(x))


# TF-IDF

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['content'])
y = df['type']



In [13]:
pd.DataFrame(X.toarray(), columns=vectorizer.vocabulary_.keys())

saf  floral  frame  paint  wood   30  inch   10  special  effect  ...  \
0      0.0     0.0    0.0    0.0   0.0  0.0   0.0  0.0      0.0     0.0  ...   
1      0.0     0.0    0.0    0.0   0.0  0.0   0.0  0.0      0.0     0.0  ...   
2      0.0     0.0    0.0    0.0   0.0  0.0   0.0  0.0      0.0     0.0  ...   
3      0.0     0.0    0.0    0.0   0.0  0.0   0.0  0.0      0.0     0.0  ...   
4      0.0     0.0    0.0    0.0   0.0  0.0   0.0  0.0      0.0     0.0  ...   
...    ...     ...    ...    ...   ...  ...   ...  ...      ...     ...  ...   
50419  0.0     0.0    0.0    0.0   0.0  0.0   0.0  0.0      0.0     0.0  ...   
50420  0.0     0.0    0.0    0.0   0.0  0.0   0.0  0.0      0.0     0.0  ...   
50421  0.0     0.0    0.0    0.0   0.0  0.0   0.0  0.0      0.0     0.0  ...   
50422  0.0     0.0    0.0    0.0   0.0  0.0   0.0  0.0      0.0     0.0  ...   
50423  0.0     0.0    0.0    0.0   0.0  0.0   0.0  0.0      0.0     0.0  ...   

       experienceth  qaud  hmd   oy  phonewindow  appsshazam  oneth  lifeus  \
0               0.0   0.0  0.0  0.0          0.0         0.0    0.0     0.0   
1               0.0   0.0  0.0  0.0          0.0         0.0    0.0     0.0   
2               0.0   0.0  0.0  0.0          0.0         0.0    0.0     0.0   
3               0.0   0.0  0.0  0.0          0.0         0.0    0.0     0.0   
4               0.0   0.0  0.0  0.0          0.0         0.0    0.0     0.0   
...             ...   ...  ...  ...          ...         ...    ...     ...   
50419           0.0   0.0  0.0  0.0          0.0         0.0    0.0     0.0   
50420           0.0   0.0  0.0  0.0          0.0         0.0    0.0     0.0   
50421           0.0   0.0  0.0  0.0          0.0         0.0    0.0     0.0   
50422           0.0   0.0  0.0  0.0          0.0         0.0    0.0     0.0   
50423           0.0   0.0  0.0  0.0          0.0         0.0    0.0     0.0   

       15gb  everyonegood  
0       0.0           0.0  
1       0.0           0.0  
2       0.0           0.0  
3       0.0           0.0  
4       0.0           0.0  
...     ...           ...  
50419   0.0           0.0  
50420   0.0           0.0  
50421   0.0           0.0  
50422   0.0           0.0  
50423   0.0           0.0  

[50424 rows x 62492 columns]

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [15]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9372335151214676


In [16]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.92      0.94      2379
           1       0.98      0.92      0.95      1750
           2       0.97      0.89      0.93      2082
           3       0.89      0.98      0.93      3874

    accuracy                           0.94     10085
   macro avg       0.95      0.93      0.94     10085
weighted avg       0.94      0.94      0.94     10085



In [17]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[2181   14   29  155]
 [   5 1611    6  128]
 [  35    3 1855  189]
 [  23   15   31 3805]]


# binary

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(binary=True)
X = vectorizer.fit_transform(df['content'])
y = df['type']
pd.DataFrame(X.toarray(), columns=vectorizer.vocabulary_.keys())


saf  floral  frame  paint  wood  30  inch  10  special  effect  ...  \
0        0       0      0      0     0   0     0   0        0       0  ...   
1        0       0      0      0     0   0     0   0        0       0  ...   
2        0       0      0      0     0   0     0   0        0       0  ...   
3        0       0      0      0     0   0     0   0        0       0  ...   
4        0       0      0      0     0   0     0   0        0       0  ...   
...    ...     ...    ...    ...   ...  ..   ...  ..      ...     ...  ...   
50419    0       0      0      0     0   0     0   0        0       0  ...   
50420    0       0      0      0     0   0     0   0        0       0  ...   
50421    0       0      0      0     0   0     0   0        0       0  ...   
50422    0       0      0      0     0   0     0   0        0       0  ...   
50423    0       0      0      0     0   0     0   0        0       0  ...   

       experienceth  qaud  hmd  oy  phonewindow  appsshazam  oneth  lifeus  \
0                 0     0    0   0            0           0      0       0   
1                 0     0    0   0            0           0      0       0   
2                 0     0    0   0            0           0      0       0   
3                 0     0    0   0            0           0      0       0   
4                 0     0    0   0            0           0      0       0   
...             ...   ...  ...  ..          ...         ...    ...     ...   
50419             0     0    0   0            0           0      0       0   
50420             0     0    0   0            0           0      0       0   
50421             0     0    0   0            0           0      0       0   
50422             0     0    0   0            0           0      0       0   
50423             0     0    0   0            0           0      0       0   

       15gb  everyonegood  
0         0             0  
1         0             0  
2         0             0  
3         0             0  
4         0             0  
...     ...           ...  
50419     0             0  
50420     0             0  
50421     0             0  
50422     0             0  
50423     0             0  

[50424 rows x 62492 columns]

**MultinomialNB** 

In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

Accuracy: 0.9464551313832424
[[2171   29   43  136]
 [   6 1711    6   27]
 [  34   11 1938   99]
 [  28   52   69 3725]]


# Counting

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(binary=False)
X = vectorizer.fit_transform(df['content'])
y = df['type']

pd.DataFrame(X.toarray(), columns=vectorizer.vocabulary_.keys())

saf  floral  frame  paint  wood  30  inch  10  special  effect  ...  \
0        0       0      0      0     0   0     0   0        0       0  ...   
1        0       0      0      0     0   0     0   0        0       0  ...   
2        0       0      0      0     0   0     0   0        0       0  ...   
3        0       0      0      0     0   0     0   0        0       0  ...   
4        0       0      0      0     0   0     0   0        0       0  ...   
...    ...     ...    ...    ...   ...  ..   ...  ..      ...     ...  ...   
50419    0       0      0      0     0   0     0   0        0       0  ...   
50420    0       0      0      0     0   0     0   0        0       0  ...   
50421    0       0      0      0     0   0     0   0        0       0  ...   
50422    0       0      0      0     0   0     0   0        0       0  ...   
50423    0       0      0      0     0   0     0   0        0       0  ...   

       experienceth  qaud  hmd  oy  phonewindow  appsshazam  oneth  lifeus  \
0                 0     0    0   0            0           0      0       0   
1                 0     0    0   0            0           0      0       0   
2                 0     0    0   0            0           0      0       0   
3                 0     0    0   0            0           0      0       0   
4                 0     0    0   0            0           0      0       0   
...             ...   ...  ...  ..          ...         ...    ...     ...   
50419             0     0    0   0            0           0      0       0   
50420             0     0    0   0            0           0      0       0   
50421             0     0    0   0            0           0      0       0   
50422             0     0    0   0            0           0      0       0   
50423             0     0    0   0            0           0      0       0   

       15gb  everyonegood  
0         0             0  
1         0             0  
2         0             0  
3         0             0  
4         0             0  
...     ...           ...  
50419     0             0  
50420     0             0  
50421     0             0  
50422     0             0  
50423     0             0  

[50424 rows x 62492 columns]

In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

Accuracy: 0.9503222607833416
[[2191   34   38  116]
 [   6 1720    9   15]
 [  34   12 1947   89]
 [  26   55   67 3726]]
